pipelines:
  ea-pipeline1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/adityasood/licensemgmt.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              elastic_profile_id:
              tasks:
               - exec: # indicates type of task
                   command: ls
