format_version: 3
environments:
  test:
    environment_variables:
      DEPLOYMENT_PASSWORD: "deployer123"
      DEPLOYMENT_USER: "deployer"
    pipelines:
      - mypipe1
    agents:
      - bcb9e13f-fb78-48f6-ac30-d6ac69459db6
pipelines:
  mypipe1: 
    group: mygroup
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      mygit:
        git: https://github.com/adityasood/gocd-yaml-config-example.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            csharp:
              tasks: # ordered list of tasks to execute in job csharp
               - exec:
                   command: /bin/bash
                   arguments:
                    - "-c"
                    - "sleep 500"